### ISSUE TITLE
Reset and or change summoner account

### ISSUE THREAD

**Issue by donnyroufs** [donnyroufs/leaguedex#34]
- [x] Option to change their currnent summoner account

#29 Should be worked on after this issue.

**Comment by CorruptComputer** [comment]
I would also like to see the ability to link multiple summoner accounts, and you could see what you've done on each.

**Comment by donnyroufs** [comment]
> I would also like to see the ability to link multiple summoner accounts, and you could see what you've done on each.

#105 there's a seperate issue for this feature!
